{% set version = "2.0.4" %}

package:
  name: go-md2man
  version: {{ version }}

source:
  url: https://github.com/cpuguy83/go-md2man/archive/v{{ version }}.tar.gz
  sha256: b0a4c7c077ede56967deef6ab7e7696c0f46124b0b3360fd05564ec5a536f11f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go >=1.11
    - go-licenses
    - make
  host:
  run:

test:
  commands:
    - echo ""|go-md2man

about:
  home: https://github.com/cpuguy83/go-md2man
  dev_url: https://github.com/cpuguy83/go-md2man
  doc_url: https://github.com/cpuguy83/go-md2man
  license: MIT
  license_file:
    - LICENSE.md
    - thirdparty-licenses.txt
  summary: Converts markdown into roff (man pages)
  description: |
    go-md2man converts standard markdown formatted documents into manpages. It is written purely in Go so as to reduce dependencies on 3rd party libs.

    By default, the input is stdin and the output is stdout.

extra:
  recipe-maintainers:
    - mbargull
